[title]
background = 30
text = 93
text_modifier = 1

[panels]
background = 98

border_active = 98
border_inactive = 30

file = 37
file_selected = 30

exec_file = 32
exec_file_selected = 30

link = 35
link_selected = 33

special_file = 31

dir = 34

hidden = 33
# selection_color = 94
selection_color = 36

header_bg = 38
# header_bg = 36
header_fg = 30

[footer]
key_code = 31
key_code_modifier = 1
key_title = 30
background = 38
